# Generated by Django 5.1.1 on 2025-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userid',
            new_name='StudentId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='LastName',
        ),
    ]
