# Generated by Django 5.1.7 on 2025-03-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_type',
            new_name='patient_type',
        ),
    ]
