# Generated by Django 5.1.7 on 2025-03-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_patient_type_patient_patient_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
