# Generated by Django 5.1.7 on 2025-03-27 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clinician_patient_medicalhistory_visit_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='customuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
