# Generated by Django 5.1.7 on 2025-03-27 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='followup',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='StudentId',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Clinician',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
